<a href="https://colab.research.google.com/github/satyanarayanaallam/tensorflow_practice/blob/main/tf_practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
print("Tensorflow version:",tf.__version__)

Tensorflow version: 2.15.0


In [4]:
mnist=tf.keras.datasets.mnist

In [5]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [6]:
x_train,x_test=x_train/255.0,x_test/255.0

In [7]:
type(x_train)

numpy.ndarray

In [8]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0,2),
    tf.keras.layers.Dense(10)
]
)

In [9]:
predictions=model(x_train[:1]).numpy()
predictions

array([[-0.07308452, -1.2938352 ,  0.6933545 , -0.09622924, -0.04516846,
         0.16222462, -0.07600877,  0.58450305, -0.2169275 , -0.02231876]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.08648171, 0.02551285, 0.18611634, 0.0845031 , 0.08892995,
        0.1094253 , 0.08622918, 0.16692097, 0.07489521, 0.09098537]],
      dtype=float32)

In [11]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1],predictions).numpy()

2.2125132

In [13]:
model.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy']
)

In [14]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2598 - accuracy: 0.9245
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1140 - accuracy: 0.9664
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0780 - accuracy: 0.9766
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0578 - accuracy: 0.9819
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0459 - accuracy: 0.9862


In [15]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 0s - loss: 0.0790 - accuracy: 0.9766 - 409ms/epoch - 1ms/step


[0.07904013991355896, 0.9765999913215637]

In [16]:
probability_model=tf.keras.models.Sequential(
    [
        model,
        tf.keras.layers.Softmax()
    ]
)

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.3425816e-09, 6.0555255e-10, 1.3428725e-07, 7.8789795e-05,
        2.5893950e-11, 1.1427530e-08, 1.2859568e-12, 9.9991846e-01,
        1.3010057e-07, 2.4988008e-06],
       [5.1323608e-09, 1.9707139e-04, 9.9936670e-01, 4.3221001e-04,
        6.1535273e-12, 5.6657502e-08, 8.9878716e-07, 1.9455334e-12,
        2.9348935e-06, 1.1486209e-13],
       [6.4118268e-07, 9.9970263e-01, 9.8624196e-06, 2.6930181e-06,
        5.3904660e-05, 2.2453176e-05, 1.9918798e-05, 9.4689567e-05,
        9.2889546e-05, 2.9356687e-07],
       [9.9987292e-01, 1.5518612e-09, 2.3736020e-05, 4.5499757e-08,
        7.1268965e-07, 1.0729713e-07, 9.5929492e-05, 2.8704169e-06,
        4.1587071e-11, 3.7392510e-06],
       [1.6422773e-06, 3.7410186e-07, 3.5752535e-06, 2.5166054e-07,
        9.6037161e-01, 1.7465394e-09, 1.8309076e-05, 2.9069546e-04,
        1.2350473e-07, 3.9313417e-02]], dtype=float32)>